### ISSUE TITLE
(suggestion) add compatibility for newer versions (1.20.5, 1.20.6 and 1.21)

### ISSUE THREAD

**Issue by Briarbot2011** [Ezzenix/ChatAnimation#13]
thanks

**Comment by Etanarvazac** [comment]
Here's the crash output when ran on 1.20.5 or newer:

```java
[07/03/2024 20:03:02 PM] java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[07/03/2024 20:03:02 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[07/03/2024 20:03:02 PM] 	at net.minecraft.class_315.<init>(class_315.java:509)
[07/03/2024 20:03:02 PM] 	at net.minecraft.class_310.<init>(class_310.java:486)
[07/03/2024 20:03:02 PM] 	at net.minecraft.client.main.Main.main(Main.java:223)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[07/03/2024 20:03:02 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[07/03/2024 20:03:02 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[07/03/2024 20:03:02 PM] 	... 10 more
[07/03/2024 20:03:02 PM] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [chatanimation.mixins.json:ChatHudMixin from mod chatanimation] from phase [DEFAULT] in config [chatanimation.mixins.json] FAILED during APPLY
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[07/03/2024 20:03:02 PM] 	... 13 more
[07/03/2024 20:03:02 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on getChatLineIndex could not find any targets matching 'Lnet/minecraft/class_338;method_1805(Lnet/minecraft/class_332;III)V' in net.minecraft.class_338. Using refmap chatanimation-refmap.json [PREINJECT Applicator Phase -> chatanimation.mixins.json:ChatHudMixin from mod chatanimation -> Prepare Injections ->  -> handler$zbi000$chatanimation$getChatLineIndex(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;I)V -> Parse]
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
[07/03/2024 20:03:02 PM] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[07/03/2024 20:03:02 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[07/03/2024 20:03:02 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
[07/03/2024 20:03:02 PM] 	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperImpl.<init>(SugarWrapperImpl.java:50)
[07/03/2024 20:03:02 PM] 	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.<init>(WrapperInjectionInfo.java:29)
[07/03/2024 20:03:02 PM] 	at com.llamalad7.mixinextras.sugar.impl.SugarWrapperInjectionInfo.<init>(SugarWrapperInjectionInfo.java:14)
[07/03/2024 20:03:02 PM] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[07/03/2024 20:03:02 PM] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[07/03/2024 20:03:02 PM] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[07/03/2024 20:03:02 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[07/03/2024 20:03:02 PM] 	... 13 more
```

**Comment by Ezzenix** [comment]
Mod is now updated.
